// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: chgk-telegram.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChgkServiceClient is the client API for ChgkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChgkServiceClient interface {
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*Empty, error)
	Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Error, error)
	GetTopPozition(ctx context.Context, in *User, opts ...grpc.CallOption) (*Error, error)
}

type chgkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChgkServiceClient(cc grpc.ClientConnInterface) ChgkServiceClient {
	return &chgkServiceClient{cc}
}

func (c *chgkServiceClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.ChgkService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chgkServiceClient) Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/api.ChgkService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chgkServiceClient) GetTopPozition(ctx context.Context, in *User, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/api.ChgkService/GetTopPozition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChgkServiceServer is the server API for ChgkService service.
// All implementations must embed UnimplementedChgkServiceServer
// for forward compatibility
type ChgkServiceServer interface {
	SendMessage(context.Context, *SendMessageReq) (*Empty, error)
	Register(context.Context, *User) (*Error, error)
	GetTopPozition(context.Context, *User) (*Error, error)
	mustEmbedUnimplementedChgkServiceServer()
}

// UnimplementedChgkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChgkServiceServer struct {
}

func (UnimplementedChgkServiceServer) SendMessage(context.Context, *SendMessageReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChgkServiceServer) Register(context.Context, *User) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedChgkServiceServer) GetTopPozition(context.Context, *User) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPozition not implemented")
}
func (UnimplementedChgkServiceServer) mustEmbedUnimplementedChgkServiceServer() {}

// UnsafeChgkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChgkServiceServer will
// result in compilation errors.
type UnsafeChgkServiceServer interface {
	mustEmbedUnimplementedChgkServiceServer()
}

func RegisterChgkServiceServer(s grpc.ServiceRegistrar, srv ChgkServiceServer) {
	s.RegisterService(&ChgkService_ServiceDesc, srv)
}

func _ChgkService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChgkServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ChgkService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChgkServiceServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChgkService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChgkServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ChgkService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChgkServiceServer).Register(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChgkService_GetTopPozition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChgkServiceServer).GetTopPozition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ChgkService/GetTopPozition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChgkServiceServer).GetTopPozition(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// ChgkService_ServiceDesc is the grpc.ServiceDesc for ChgkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChgkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ChgkService",
	HandlerType: (*ChgkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChgkService_SendMessage_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ChgkService_Register_Handler,
		},
		{
			MethodName: "GetTopPozition",
			Handler:    _ChgkService_GetTopPozition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chgk-telegram.proto",
}
